Ignore lock files and other dead symlinks
garybernhardt/serveit pull request #10
Opened 2019-03-06 11:44 UTC by dpk

Emacs creates lock files — symbolic links which contain a process identifier — when you start modifying a file but haven’t yet saved it. These would cause serveit to produce a 500 error, because it tries to stat the referent of these symlinks, which is by design a nonexistent file.

More generally this will stop the server coming up with a 500 error whenever the directory structure which is being watched contains a symbolic link to a file which doesn’t exist.

2019-03-07 20:00 UTC, garybernhardt requested changes

2019-03-07 20:00 UTC, garybernhardt commented on serveit
> +    def lock_file?(path)
I think this should be named something like `missing_symlink_target?`, since there's nothing inherently related to lock files in it.

2019-03-07 20:00 UTC, garybernhardt commented on serveit
> +      File.symlink?(path) \
The `\` and `and not` aren't idiomatic here. Maybe something like:

```
is_symlink = ...
return false unless is_symlink
return [check for whether symlink target exists]
```

2019-03-09 11:46 UTC, dpk commented
I’ve made the changes requested. Should I squash the commits before you merge?

2019-03-12 19:42 UTC, garybernhardt approved these changes

2019-03-12 19:51 UTC, garybernhardt commented
Squashed as 6e202aa, thanks!

2019-03-12 19:51 UTC, closed without merging

2019-03-12 21:01 UTC, garybernhardt commented
I just opened a PR with homebrew: https://github.com/Homebrew/homebrew-core/pull/37835

Once they merge it, you should be able to upgrade your installed serveit from homebrew to get this and the port option.